### ISSUE TITLE
at_c: atsign type

### ISSUE THREAD

**Issue by JeremyTubongbanua** [atsign-foundation/at_c#107]
A typedef struct holding an atsign that ensures correct format

To be used in functions that use atsigns (for example, atkey).

**Comment by JeremyTubongbanua** [comment]
Some discussion has already been made here:

@XavierChanth believes less is more in that we should keep atclient_atsign_without_at at most

@realvarx wants atsign struct to hold two things: 1 a string to the atsign, and 1 string to hold atsign wtihout prefix'd @ symbol for quick access

I believe we should have 1 string to the atsign (an atclient_atstr) then a char pointer to the character after the `@` symbol, so we can use the memory of just 1 string and also have quick access to the atsign without `@` sign

**Comment by xavierchanth** [comment]
option 3 makes a lot of sense to me
