### ISSUE TITLE
at_c: rename atkey.name to atkey.key in atkey struct (atkey.h) to be consistent with dart

### ISSUE THREAD

**Issue by JeremyTubongbanua** [atsign-foundation/at_c#154]
@XavierChanth had a comment on this in #151

**Comment by xavierchanth** [comment]
We don't have to make this change, especially since it's a breaking one, and we definitely don't have to make this change now. but it is worth something noting, possibly on a breaking changes list issue.

**Comment by JeremyTubongbanua** [comment]
I personally believe it's something we should do now while the SDK is in alpha @XavierChanth

**Comment by cpswan** [comment]
Until we get to 1.0 there shouldn’t be too much concern about ‘breaking’
