### ISSUE TITLE
at_c: chore to rename shared_by and shared_with static functions in atclient.c

### ISSUE THREAD

**Issue by JeremyTubongbanua** [atsign-foundation/at_c#168]
@realvarx based on our conversation in Zoom

Change title of the static functions that _get_sharedkey uses, so that it is more readable and understandable that it *returns* the value

**Comment by realvarx** [comment]
@JeremyTubongbanua how does the following sound?:

Change:
`atclient_get_shared_by_me_with_other`
`atclient_get_shared_by_other_with_me`

By:
`atclient_get_sharedkey_shared_by_me_with_other`
`atclient_get_sharedkey_shared_by_other_with_me`
