### ISSUE TITLE
C++ SDK platform/framework wrappers

### ISSUE THREAD

**Issue by XavierChanth** [atsign-foundation/at_c#2]
*Implementation of the C++ SDK is dependent on this to be completed.*

What needs to be done:

- [ ] Define the functionality required from dependencies of the C++ SDK
- [ ] Define and prioritize the platforms and frameworks and we would like to support
- [ ] Implement platform/framework specific wrappers around each dependency
- [ ] Expose each platform/framework wrapper under a normalized interface

**Comment by xavierchanth** [comment]
Currently implementing an encryption interface for the library.

- base64 encode/decode is implemented
- aes ctr encrypt/decrypt in progress

Struggling to find any documentation for aes ctr encrypt/decrypt in MBedTLS.
