### ISSUE TITLE
Functional tests fail on Dependabot PRs as atKey secrets aren't available.

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/at_c#230]
### Describe the bug

Runs such as https://github.com/atsign-foundation/at_c/actions/runs/8983193176/job/24672600212 fail because the atKeys are empty because secrets aren't available to Dependabot.

### Steps to reproduce

1. First Dependabot raises a PR
2. Then tests run
3. And then functional tests fail
4.

### Expected behavior

Tests should pass (or be bypassed where it isn't safe for secrets to be available)

**Comment by JeremyTubongbanua** [comment]
I added the atkeys secrets to the dependabot repository secrets

Close this ticket if Dependabot PRs no longer cause functional tests to fail

**Comment by cpswan** [comment]
#268 seems to suggest that we're fine. Thanks @JeremyTubongbanua
