### ISSUE TITLE
at_c: passing a `NULL` into `atserver_host` and `0` into `atserver_port` will use `atclient_utils_find_atserver_address`

### ISSUE THREAD

**Issue by JeremyTubongbanua** [atsign-foundation/at_c#285]
This is a nice QOL feature.

- passing a NULL into atserver_host
- passing 0 into atserver_port 
- will use atclient_utils_find_atserver_address

So that the person using `atclient_pkam_authenticate` won't have to manage atserver_host and atserver_port

**Comment by sitaram-kalluri** [comment]
@JeremyTubongbanua :

To ensure that atserver_host and atserver_port are correctly populated when null and 0 are passed, we require root_server_host and root_server_port. For atclient_pkam_authenticate to set these values appropriately, we have two options:

1. Pass root_server_host and root_server_port as arguments to atclient_pkam_authenticate function.

2. Define a structure containing root_server_host and root_server_port, and pass this structure as an argument to atclient_pkam_authenticate function.

The latter approach is preferable because it allows us to add more parameters in the future without introducing breaking changes.

**Comment by JeremyTubongbanua** [comment]
> sitaram-kalluri

Great suggestion! 

I am for the idea of making an `atclient_pkam_authenticate_options` struct where definition looks like this:

```c
typedef struct atclient_pkam_authenticate_options {
    char *atserver_host;
    int atserver_port;
} atclient_pkam_authenticate_options;
```

and the `atclient_pkam_authenticate` function signature would look like this:

```c
int atclient_pkam_authenticate(atclient *atclient, const char *atsign, atclient_atkeys *atkeys, atclient_pkam_authenticate_options *options);
```

Some notes;

- *options is a pointer so that the developer can pass `NULL`, and the function will fall back to our default values.
- *atkeys remains as part of the function signature as a required argument because we initially wanted the developer journey to involve fetching the atkeys themselves. Embedded devices may not always have their atKeys located in the `~/.atsign/keys/` folder. And the developer may have multiple `atclient` contexts within the same program that use the same set of keys, so it would make sense to pass a pointer to those keys as to not have to duplicate memory.

Overall developer implementation would look like this:

```c
int ret = 1;

atclient_atkeys atkeys;
atclient_atkeys_init(&atkeys);

atclient ctx;
atclient_init(&ctx);

if ((exit_code = atclient_utils_populate_atkeys_from_homedir(&atkeys, "@alice")) != 0)
{
    // error
}

if((ret = atclient_pkam_authenticate(&atclient, &atkeys, "@alice", NULL)) != 0) {
    // error
}

atclient_atkeys_free(&atkeys);
atclient_free(&atclient);
```

OR

```c
int ret = 1;

atclient_atkeys atkeys;
atclient_atkeys_init(&atkeys);

atclient ctx;
atclient_init(&ctx);

atclient_pkam_authenticate_options options;
atclient_pkam_authenticate_options_init(&options);

if((exit_code = atclient_pkam_authenticate_options_set_atserver_host(&options, "abc.123")) != 0) {
    // malloc error
}

if((exit_code = atclient_pkam_authenticate_options_set_atserver_port(&options, 55)) != 0) {
    // error
}


if ((exit_code = atclient_utils_populate_atkeys_from_homedir(&atkeys, "@alice")) != 0)
{
    // error
}

if((ret = atclient_pkam_authenticate(&atclient, &atkeys, "@alice", &options)) != 0) {
    // error
}

atclient_atkeys_free(&atkeys);
atclient_free(&atclient);
atclient_pkam_authenticate_options_free(&options);
```

**Comment by JeremyTubongbanua** [comment]
Let me know your thoughts :) @sitaram-kalluri

**Comment by sitaram-kalluri** [comment]
> Let me know your thoughts :) @sitaram-kalluri 

@JeremyTubongbanua : Looks good to me. Will start implementing it.

**Comment by JeremyTubongbanua** [comment]
> > Let me know your thoughts :) @sitaram-kalluri
> 
> @JeremyTubongbanua : Looks good to me. Will start implementing it.

Awesome,

Take a look at `notify_params.c` and the pattern of how I implemented setters/getters

Each field has a:
- `*_set_*` function - which copies (malloc) the value and stores it
- `*_unset_*` function - which frees the value, if it was initialized
- `*_is_*_initialized` function - which has a unique way of tracking if `*_set_*` was called at some point in time. This could be tracked with a bit/boolean flag.
- `*_set_*_initialized` function - which is a static helper function for `*_unset_*` and `*_set_*` to utilize.

If you don't agree with this implementation, feel free to implement it in a way you're confident in

**Comment by JeremyTubongbanua** [comment]
Then the struct as a whole has

- `_init` function - which `memset()` the struct to 0's and sets any default values, it is important that this is `void` and is immune to any errors (that is not the developer's fault)
- `_free` function - which frees anything that may have been malloc'd throughout the struct's lifetime

I also did not mention how we `get` values:

```c
// It isn't safe to do this:
printf("%s\n", options->atserver_host);
```

```c
// We should check if it was initialized first and non-null before printing:
// This is how I expect the developer to utilize the is_initialized function to ensure that it is safe for reading and does not contain garbage values
if(atclient_pkam_authenticate_options_is_atserver_host_initialized(&options) && options->atserver_host != NULL) {
    printf("%s\n", options->atserver_host);
}
```
