### ISSUE TITLE
support auth with apkam atKeys file

### ISSUE THREAD

**Issue by gkc** [atsign-foundation/at_c#287]
### Is your feature request related to a problem? Please describe.

apkam atKeys files contain the APKAM enrollment ID which should be included in the pkam command that the client sends. The enrollment ID is required by the atServer in order to locate the APKAM public key for this enrollment, which it then uses to verify the signature.  Currently the enrollment ID is not sent, therefore the signature verification fails.

### Describe the solution you'd like

When reading atKeys json
- check if there is an enrollment ID in the json
- if an enrollment ID is present, then use it when generating the pkam command which is sent to the atServer

**Comment by JeremyTubongbanua** [comment]
I wrote the atKeys code for the C SDK, so I'd be happy to be assigned this ticket

**Comment by JeremyTubongbanua** [comment]
cc @gkc 

Assigning P2 and 2 SP

**Comment by JeremyTubongbanua** [comment]
Related data: https://github.com/atsign-foundation/at_libraries/blob/d764cc4e8753da294728dbe65d697ac32fce1247/packages/at_commons/lib/src/verb/pkam_verb_builder.dart#L23

**Comment by JeremyTubongbanua** [comment]
There is work in #400 for this ticket
