### ISSUE TITLE
at_c: matrix CI on multiple platforms

### ISSUE THREAD

**Issue by JeremyTubongbanua** [atsign-foundation/at_c#307]

**Comment by xavierchanth** [comment]
linux / macos

clang / gcc

**Comment by xavierchanth** [comment]
To be discussed in arch

**Comment by xavierchanth** [comment]
This is actually not 1 story point... because we don't run any of the actual e2e tests in the GitHub actions runners. We could run the c build steps as a sanity check, but we wouldn't be able to do much else without major changes to the e2e test environment.

**Comment by xavierchanth** [comment]
For this reason, I am going to close this ticket. We haven't even committed to a standard set of builds yet for the C daemon, so any effort here is most likely pointless, and definitely time consuming.
