### ISSUE TITLE
at_c: remove atclient_atsign and use char * to represent atSigns instead

### ISSUE THREAD

**Issue by JeremyTubongbanua** [atsign-foundation/at_c#336]
We had this conversation before and just wanted to get it in writing:

We currently don't use `atclient_atsign` everywhere in our function signatures, but if we were to commit to it, it would be a lot of the following 3 lines of code:

```c
atclient_atsign atsign;
atclient_atsign_init(&atsign, "@alice");

// ...

atclient_atsign_free(&atsign);
```

Here's an image of where we use atclient_atsign right now, and it quickly becomes a tedious step to have to create an atSign object every single time.

![image](https://github.com/atsign-foundation/at_c/assets/79019866/c33418e0-e28f-409e-9022-e8ed13069e7f)

I would like to propose that we eliminate the `atclient_atsign` struct completely because it is always a preliminary chore step to have to create this struct in order to pass atSign string data into a function. 

Then every time we would have to validate if an atSign string is valid, we would use a function to do the check. This is the current pattern we use in Dart.

**Comment by realvarx** [comment]
I agree, there aren't many parts where we are still using it. If we decide to reintroduce it in the future for some reason, it shouldn't be complicated

**Comment by JeremyTubongbanua** [comment]
We've got +2 for deciding on removing atclient_atsign altogether.

Will be editing the title and allocating SP.
