### ISSUE TITLE
Update CMake minimum required version to 3.24

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/at_c#338]
Features that use 3.24:
- Policy CMP0135
- find_package's fetch content redirection search mode

Debian derivatives are problematic with this version of cmake since the system packages are older versions. The solution is to use pip to install cmake, but you may also need to install to a venv if you are on debian 12, as system packages are not supported with pip.

**Comment by JeremyTubongbanua** [comment]
Related articles:

PR when we set policy CMP0135 to NEW: https://github.com/atsign-foundation/at_c/pull/68

Issue of why we changed cmake minimum version to 3.19: https://github.com/atsign-foundation/at_c/issues/23
