### ISSUE TITLE
at_c: discussion on moving `atchops_md_type` to `sha.h`

### ISSUE THREAD

**Issue by JeremyTubongbanua** [atsign-foundation/at_c#346]
This is `constants.h` right now:

```h
#ifndef ATCHOPS_CONSTANTS_H
#define ATCHOPS_CONSTANTS_H

#define ATCHOPS_RNG_PERSONALIZATION "@atchops12345"

#include "mbedtls/md.h"

typedef enum atchops_md_type {
  ATCHOPS_MD_NONE = 0,
  ATCHOPS_MD_MD5,
  ATCHOPS_MD_RIPEMD160,
  ATCHOPS_MD_SHA1,
  ATCHOPS_MD_SHA224,
  ATCHOPS_MD_SHA256,
  ATCHOPS_MD_SHA384,
  ATCHOPS_MD_SHA512,
  ATCHOPS_MD_SHA3_224,
  ATCHOPS_MD_SHA3_256,
  ATCHOPS_MD_SHA3_384,
  ATCHOPS_MD_SHA3_512,
} atchops_md_type;

extern const mbedtls_md_type_t atchops_mbedtls_md_map[];

#endif

```

In the perspective of the person using our atSDK, If I wanted to use a variable like `ATCHOPS_MD_SHA256`, I would expect to have to do `#include<atchops/sha.h>` as opposed to `#include<atchops/constants.h>`

## Proposal

Move the MD stuff from `constants.h` to `sha.h`

**Comment by JeremyTubongbanua** [comment]
@XavierChanth Would like your input

**Comment by xavierchanth** [comment]
I think this needs some more thought first. Notice the mbedtls stuff in the header file. We should wrap the extern const map in this file into an atchops/mbedtls.h file. I think the enum can move to atchops/sha.h though.

**Comment by JeremyTubongbanua** [comment]
I agree with an `atchops/mbedtls.h`
