### ISSUE TITLE
at_c: C atSDK Contributing Specification

### ISSUE THREAD

**Issue by JeremyTubongbanua** [atsign-foundation/at_c#350]
# Convention 1. Snake Case

## Description

We're using snake case instead of camel case because MbedTLS happens to be snake case. Since MbedTLS is one of our core libraries seen everywhere, we may as well follow their naming convention.

When using snake case, we separate each **word** with an underscore.

## Examples

Good:

```c
aes_pkam_public_key
value_encrypted_for_us_base64
atclient
atsign
```

Bad:

```c
aespkampublickey
skeencalgo
at_client
at_key
HelloWorld
helloWorld
```

## Exceptions

Some exceptions that you may find throughout the code base:

- We consider `base64` as one word because "64" isn't really a word
- When we use the `at` prefix, we do not consider it as a word which is why we have `atclient` instead of `at_client`. There are just too many ats that an extra underscore would be too much to type.

# Convention 2. Function Signature Format

## Description

Functions should return an `int` to hand off an error code to the caller of the function. If an error is not possible, void should be used (exception on this will emphasized later).

Example of a function:

```c
int calculate_length(const atclient_atkey *atkey, int *output_length);
```

Generally, function signatures should follow this format:

```c
<return_type> <function_name>(<context>, <input,..>, <output,...>);
```

- <return_type> - generally an `int` to give an error code, or may be any other return type as long as a complex error is not possible 
- <function_name> - the name of the function (example 'foo_bar') should be in snake_case
- <context> - typically this is a struct pointer that is the core object meant to be used in the function (i.e. this function LIVES and BREATHES because of the object that the caller is passing), this should be set to `const` if it is meant to be read-only
- <input,..> - any input function arguments, any values that are not editable or should not be edited, should be set to `const`.
- <output,..> - any output function arguments, typically we have pointers or double pointers to give the caller some complex values, any const inputs that are related to the output should be put in this section (for example, buffer size is related to the buffer, which is an output).

Here are some examples:

```c
// function signature
int lemonade(atclient *ctx, const char *value, char **commit_id);
```

```c
// usage
atclient ctx; // assume ctx is set up properly (initialized, authenticated, and yada yada)
char *commit_id = NULL;
atclient_put(&ctx, "foo_bar", &commit_id);
printf("%s\n", commit_id); // outputs "37", for example
free(commit_id);
```

# Convention 3. Function Input

Related discussions have been made in : #341

## Description

This section is regarding the `<input,...>` section of the function signature.

When receiving input in a function signature, when is it appropriate to pass the length of the buffer and when is it not?

Take the following example

```c
// method 1 - assume it is null-terminated
int do_something1(const char *value);

// method 2 - expect value length as input
int do_something(const char *value, const size_t value_len);
```

## Method 1

In method 1, take the input and expect it to be null-terminated

Use method 1 when:
- Working with strings (chars)
- You specify that the input should be null-terminated and it is the caller's responsibility to pass in a null-terminated string

## Method 2

In method 2, take both the input and length

Use method 2 when:

- Working with bytes (unsigned chars) - a null-terminator cannot be dependent to act as the end of the data
- Working with files or standard input - when the caller is most likely passing in this data from a file, it will be a lot easier for them to pass the length as opposed to having to make a completely separate string and null-terminate it.

# Convention 4. Function Output

Related discussions have been made in : #335

## Description

This section is regarding the `<output,...>` section of the function signature.

There are two ways to give back an array of data back to the caller of the function. The first way is **double pointer method** and the second way is **buffer and length**. 

In the first way, the **function** is responsible for allocating the memory and the **caller** is responsible for freeing. In the second way, the **caller** is responsible for both allocating and freeing the memory.

The third way is very similar to the second method, but the function does not return the length.

## Double Pointer Method

In this first method, you pass a double pointer so that the function can allocate **just enough** memory for you, making your life easier while also optimally using your memory.

```c
// function signature
int atclient_atkey_to_string(const atclient_atkey *atkey, char **return_string);
```

```c
// usage
char *string = NULL;

atclient_atkey_to_string(&atkey, &string);

printf("%s\n", string); // outputs "foo.bar@bob"

free(string);
```

You should use this method when:

- Returning a string (this is most optimal for strings because a null-terminator can be used to avoid passing a length)
- Output is calculable (if we know how long the string is going to be, we know where to put the null-terminator !)
- The returned data is a substring of a superior buffer (example, I want to return "foo" from "foo_bar", "foo" is trivial to extract from the string and should be simplified for the caller).

## Buffer And Length Method

In this second method, the caller has more control over the memory usage (e.g. they could allocate it statically or dynamically if they would like!), but is a lot harder to use. In the example below, the caller has to go through and allocate the memory, reset the buffer, and make a variable to hold the length.

```c
// function signature
int atclient_atkey_to_string(const atclient_atkey *atkey, char *return_buffer, const size_t return_buffer_size, size_t *return_buffer_len);
```

Sometimes, `size_t *return_buffer_len` is an optional buffer and NULL can be passed here if the caller doesn't want to receive the length. This is useful for when the caller null-terminates the buffer themselves and can trust that the buffer will be null-terminated and safe for string usage.

```c
// usage
const size_t string_size = 100;
char string[string_size];
memset(string, 0, sizeof(char) * string_size);
size_t string_len = 0;

atclient_atkey_to_string(&atkey, string, string_size, &string_len);

printf("[%d]: %.*s\n", (int) string_len, (int) string_len, string); // outputs "[11]: foo.bar@bob"
```

You should use this method when:

- Returning bytes (a null-terminator cannot be depended on to act as a stopping point in the buffer)
- Output is not calculable (let the caller decide how much memory is enough to not cause a segfault, this is typically found in something like RSA decryption)
- When the input is most likely coming from a file (makes it easier to pass in strings so that the caller doesn't have to make separately null-terminated strings and easily do something like foo_bar(string[3], 10, string[14], 5, string[20], 3); )

## Buffer and No Length

This third method is very similar to the second way, except there is no need to pass a `size` and `output_length` pointer. It should be specified in **function documentation** the assumed size of the allocated buffer as well as the expected output.

```c
// function signature

/**
 * @param shared_with - shared with atSign, null-terminated and non-null
 * @param shared_encryption_key - assumed to be at least 32 bytes allocated (representing an AES256 key)
 */
int get_shared_encryption_key(const char *shared_with, unsigned char *shared_encryption_key);
```

```c
// usage
const char *shared_with = "@bob";
unsigned char shared_encryption_key[32];
if((ret = get_shared_encryption_key(shared_with, shared_encryption_key)) == 0) {
    // at this point, shared_encryption_key was successfully populated with 32 bytes to the brim
}
```

You should use this method when
- You wanted to use Method 2 but the size and length are always the same (in the example above, the size always == length and is always 32, assuming that the return exit code was 0 which means successful).
- You're not returning a string, you're returning bytes (unsigned chars)

# Convention 5. Validating arguments

# Convention 6. Why we don't typedef our enums

# Convention 7. Error Handling

1. Default error code is first line of any function
2. Try to avoid non-nested if statements. If an error occurs, then set the error code if it is not already set by the function, log, then either exit or return

# Convention 8. Why variables are at the top of the function

**Comment by cpswan** [comment]
@JeremyTubongbanua this should be added to contributing.md (perhaps also with a note in README.md pointing to it and maybe listing the sections).

If there are decisions to be made here then let's have a draft ADR (but it looks to me like everything's pretty much decided).

**Comment by JeremyTubongbanua** [comment]
> @JeremyTubongbanua this should be added to contributing.md (perhaps also with a note in README.md pointing to it and maybe listing the sections).
> 
> If there are decisions to be made here then let's have a draft ADR (but it looks to me like everything's pretty much decided).

Yep, will have it properly put in Contributing.MD and update the rood README.md

I'll also have an ADR put up.
