### ISSUE TITLE
at_c: change `atclient_pkam_authenticate` function signature

### ISSUE THREAD

**Issue by JeremyTubongbanua** [atsign-foundation/at_c#377]
Our C specification states that we should have optional arguments at the end of the function signature:
![image](https://github.com/user-attachments/assets/75f5c079-5afa-40f7-8a69-bdd9c46028fb)

To stay true to that, the atclient_pkam_authenticate function signature should be changed to the following:

```c
int atclient_pkam_authenticate(atclient *ctx, const char *atsign, const char *atserver_host, const int atserver_port,
                               const atclient_atkeys *atkeys)
```

This is how it is currently:

```c
int atclient_pkam_authenticate(atclient *ctx, const char *atserver_host, const int atserver_port,
                               const atclient_atkeys *atkeys, const char *atsign)
```

The reason for this change is because of ticket #285 , which states that `atserver_host` and `atserver_port` may soon be optional arguments. `atclient_atkeys` may also soon be an optional argument as well and the function will do all the heavy lifting for the developer.

This will be a breaking change which is why I am setting this ticket as P4 (Informational) as a reminder for when we consider doing a stable release.

**Comment by cpswan** [comment]
@JeremyTubongbanua whilst we're still at v0.x.y it's fine for us to do breaking changes with just a bump to minor. Only after we do v1 do we then need to start bumping major.

**Comment by JeremyTubongbanua** [comment]
> e're still at v0.x.y it's fine for us to do breaking changes with just a bump to minor. Only after we do v1 do we then need to star

Awesome! Thanks for the assist

**Comment by JeremyTubongbanua** [comment]
Done in #381
