### ISSUE TITLE
C++ SDK cross-compilation build system

### ISSUE THREAD

**Issue by XavierChanth** [atsign-foundation/at_c#4]
What needs to be done:

- [x] Based on #2's determined platforms/frameworks implement build tooling support for each
- [x] Provide archetypes and examples for each platform/framework
- [x] Write tests and CI to confirm that the project builds correctly on all platforms

**Comment by xavierchanth** [comment]
archetypes in progress, tests for desktop/mbedtls are coming together with the development of the encryption interface.

**Comment by JeremyTubongbanua** [comment]
There are examples to build for desktop using CMake as well as examples for building for ESP-IDF with choice to use local source code OR use static librares and headers
