### ISSUE TITLE
The no-ports end-to-end tests fail when executed with atSigns that are not production atSigns.

### ISSUE THREAD

**Issue by sitaram-kalluri** [atsign-foundation/at_c#414]
### Describe the bug

In "main.c",since null is passed to the atclient_utils_find_atserver_address() function in "atclient.c", the default values of production root server and port are used. Hence the test pass. However, during local testing, if options are provided to the monitor_pkam_authenticate method (the last parameter in method), the atdirectory_host and atdirectory_port, corresponding to the root server and port, are assigned to atserver_host and atserver_port. This leads to the test failure.

Additionally, the "atclient_utils_find_atserver_address" method always sets the root server details to the production host and port. Any alternative root server and port provided through the atclient_pkam_authenticate_options are ignored.

noports/packages/c/sshnpd/src/main.c
```
res = atclient_monitor_pkam_authenticate(&monitor_ctx, params.atsign, &atkeys, NULL);
```

packages/atclient/src/atclient.c-> atclient_pkam_authenticate()
```
if (options != NULL) {
    if (atclient_pkam_authenticate_options_is_atdirectory_host_initialized(options) &&
        atclient_pkam_authenticate_options_is_atdirectory_port_initialized(options)) {
      atserver_host = options->atdirectory_host;
      atserver_port = options->atdirectory_port;
    }
  }

  if (atserver_host == NULL || atserver_port == 0) {
    atlogger_log(TAG, ATLOGGER_LOGGING_LEVEL_INFO,
                 "Missing atServer host or port. Using production atDirectory to look up atServer host and port\n");
    if ((ret = atclient_utils_find_atserver_address(ATCLIENT_ATDIRECTORY_PRODUCTION_HOST,
                                                    ATCLIENT_ATDIRECTORY_PRODUCTION_PORT, atsign, &atserver_host,
                                                    &atserver_port)) != 0) {
      atlogger_log(TAG, ATLOGGER_LOGGING_LEVEL_ERROR, "atclient_utils_find_atserver_address: %d\n", ret);
      goto exit;
    }
    // only free this memory if it was allocated internally (by atclient_utils_find_atserver_address)
    should_free_atserver_host = true;
  }
```

Log snippet of test failure:

```
Verbose mode enabled
[DEBG] 2024-09-30 13:45:35.769157 | sshnpd | Using atkeysfile: /home/sitaram/.atsign/keys/@bob🛠_key.atKeys
[DEBG] 2024-09-30 13:45:35.838057 | connection | 	SENT: "bob🛠"
[DEBG] 2024-09-30 13:45:35.838395 | connection | 	RECV: "vip.ve.atsign.zone:25003"
[INFO] 2024-09-30 13:45:35.838444 | atclient | Missing atServer host or port. Using production atDirectory to look up atServer host and port
[DEBG] 2024-09-30 13:45:37.368938 | connection | 	SENT: "bob🛠"
[DEBG] 2024-09-30 13:45:37.675274 | connection | 	RECV: "null"
[ERROR] 2024-09-30 13:45:37.675314 | atclient_utils | Failed to parse port from atdirectory response
```

### Steps to reproduce

Run no-ports e2e tests with local atSigns.

Steps to run noports e2e tests locally:

In a NoPorts repo clone

    - build the binaries (cd /path/to/noports/packages/dart/sshnoports; buildBinaries)
    - run an srvd
        - bin/srvd -a @chuck --root-domain vip.ve.atsign.zone --ip 127.0.0.1 -v
    - run the e2e tests
         - /path/to/noports_repo/tests/e2e_all/scripts/main.sh @alice @bob @chuck -w 5 -r vip.ve.atsign.zone

### Expected behavior

For the "atclient_pkam_authenticate", if null is passed for "atclient_pkam_authenticate_options" then the default values should be considered. If options are set, the root server and port from the options should be used to fetch the secondary server address.

**Comment by JeremyTubongbanua** [comment]
I can pick this up

**Comment by sitaram-kalluri** [comment]
> I can pick this up

Thanks @JeremyTubongbanua
