### ISSUE TITLE
at_c: atclient notifications

### ISSUE THREAD

**Issue by JeremyTubongbanua** [atsign-foundation/at_c#43]
Requirements:

- [x] #82 
- [x] #83 
- [x] #45 
- [x] #111

**Comment by JeremyTubongbanua** [comment]
Currently blocked until other dependent tickets have been completed

**Comment by ksanty** [comment]
@JeremyTubongbanua how many SP's would you like to add?

**Comment by JeremyTubongbanua** [comment]
> @JeremyTubongbanua how many SP's would you like to add?

sorry, i've removed this ticket from this sprint.

this ticket is currently blocked by two other tickets

**Comment by xavierchanth** [comment]
Reducing to 2 SP, I have an MVP /example for this completed, but we need to write some tests and  potentially add further examples.
