### ISSUE TITLE
at_c: free() major bug

### ISSUE THREAD

**Issue by JeremyTubongbanua** [atsign-foundation/at_c#46]
It is possible for free() executions to occur in most functions when the variable was never allocated.

**Comment by realvarx** [comment]
It could be solved by moving all the declarations and memory allocations to a point before the `goto` sentences

**Comment by JeremyTubongbanua** [comment]
Assigning 2 SP;

Work involves going through each function and moving declarations near the top of the function. 

Cases where the function is called will not be so memory efficient (as we are allocating memory that we ultimately do not use in the event of an error), but I think it would be safe to assume heavy memory intensive functions used in embedded devices will be used correctly most of the time. Some proper checking can be done on the atclient layer (the layer above atchops) to ensure input is correct before calling a memory-intensive function.
